INSERT INTO Error_log (resource_id, error, error_code, description, module, error_level) VALUES
((SELECT id FROM Resources WHERE name = 'LoginForm'), 
'Authentication Failed', 
401, 
'User credentials validation failed after 3 attempts. Session blocked temporarily for security purposes.',
'Authentication',
'ERROR'),

((SELECT id FROM Resources WHERE name = 'WeightInput'), 
'Invalid Input Format', 
400, 
'User attempted to input non-numeric value in weight field. Input validation caught and prevented the submission.',
'Form Validation',
'WARNING'),

((SELECT id FROM Resources WHERE name = 'SaveChanges'), 
'Database Connection Lost', 
503, 
'Connection to user profile database timed out while attempting to save changes. Changes were not persisted.',
'Database',
'CRITICAL'),

((SELECT id FROM Resources WHERE name = 'UserAvatar'), 
'Image Upload Failed', 
415, 
'User attempted to upload unsupported file format. Only JPG, PNG formats are supported.',
'File Upload',
'WARNING'),

((SELECT id FROM Resources WHERE name = 'ProgressChart'), 
'Data Fetch Error', 
404, 
'Unable to retrieve user progress data for chart rendering. Data points missing for specified date range.',
'Data Service',
'ERROR'),

((SELECT id FROM Resources WHERE name = 'ProfileMenu'), 
'Component Load Timeout', 
408, 
'Profile menu component failed to load within expected timeframe. Client-side rendering timeout.',
'UI Component',
'WARNING'),

((SELECT id FROM Resources WHERE name = 'SubmitWorkout'), 
'Request Payload Too Large', 
413, 
'Workout submission contained excessive data volume. Request exceeded maximum allowed payload size.',
'API Gateway',
'ERROR'),

((SELECT id FROM Resources WHERE name = 'WorkoutCard'), 
'Render Failed', 
500, 
'Unexpected error occurred while rendering workout details. Component state corruption detected.',
'Frontend',
'CRITICAL'),

((SELECT id FROM Resources WHERE name = 'AcceptTerms'), 
'API Endpoint Unreachable', 
502, 
'Terms acceptance request failed to reach backend service. Gateway timeout occurred during request routing.',
'Network',
'ERROR'),

((SELECT id FROM Resources WHERE name = 'LogoutButton'), 
'Session Invalidation Failed', 
417, 
'User session could not be properly terminated. Token revocation service unavailable.',
'Session Management',
'WARNING');
